### ISSUE TITLE
WebP Format is Missing in 'Save As...'

### ISSUE THREAD

**Issue by MS00-GitIt** [webmproject/WebPShop#1]
![WebPFormatMissing](https://user-images.githubusercontent.com/20635110/62595069-caed2100-b8aa-11e9-9b28-b6bc078fb27a.png)

### [OBSERVED BEHAVIOR] 
When trying to save ABC.psd file the option to select WebP from the drop-down list is missing.
UI does not appear to adjust the image.

Note: WebP is available to select from 'Open'.

### [EXPECTED BEHAVIOR]
WebP should be available in the drop-down list. 

### [TROUBLESHOOTING STEPS TAKEN]
1. Uninstalled plugin version 2.1 and reinstalled 2.1. 
2. Uninstalled plugin version 2.1 and installed 2.0.

### [SYSTEM INFO]
OS: Windows 10 version 1809 x64
App: Adobe Photoshop Version: 20.0.3 x64

**Comment by y-guyon** [comment]
Thanks for the detailed bug report!
My first guess would be that the Image > Mode is not "RGB color", which is currently the only supported color mode by WebPShop (as described in [Limitations](https://github.com/webmproject/WebPShop#limitations)). PNG is not in the list either.
Could you check if converting to this color mode first solves the issue?
Alternatively, could you Open an existing WebP file (by example [this one](https://www.gstatic.com/webp/gallery/1.webp)) with Photoshop and try to Save as...?

**Comment by MS00-GitIt** [comment]
You were correct!
I was not in RGB color mode.
In the future I will make sure to read ALL of your documentation.
