### ISSUE TITLE
Doesn't load in latest Photoshop 2020

### ISSUE THREAD

**Issue by jh20001** [webmproject/WebPShop#11]
Latest Windows 10, latest Photoshop version. Adding the 8bi file into the plugins folder just like any other plugin results in nothing. Look up system info from the about menu and it doesn't show the plugin loaded. 

However, if I install the 2015 "WebP for Photoshop v0.5b9" plugin from https://github.com/fnordware/AdobeWebM page, Photoshop sees it just fine, loads it and can work with webp images. So it's just WebPShop that isn't working for some reason. 

I thought I'd point it out :)

**Comment by kmoser** [comment]
I have a similar issue: I tried version 0_3_0 and 0_2_1 (both x64) and neither was recognized by Photoshop. My Photoshop is fairly new but not the latest: version 20.0.5 20190605.r.83 2019/06/05: 1206907 x64.

The AdobeWebM (fnordware) version works for me, but I'd like to use this version (WebPShop) because it has a preview feature which makes it nicer.

**Comment by y-guyon** [comment]
Thank you for the report. I am unable to reproduce the issue with Photoshop 21.1.2 x64 on Windows Server 2016. Putting [`WebPShop_0_3_0_Win_x64.8bi`](https://github.com/webmproject/WebPShop/releases/download/v0.3.0/WebPShop_0_3_0_Win_x64.8bi) in any of these locations works:

- C:\Program Files\Common Files\Adobe\Plug-Ins\CC
- C:\Program Files\Common Files\Adobe\Plug-Ins\CC\File Formats
- C:\Program Files\Adobe\Adobe Photoshop 2020\Plug-ins

Could you try them all? You might also check that the file permissions are correct (same ones as the working plugin) and that the plugin is not loaded twice (conflicting with itself or with another WebP plugin).

Unfortunately I do not know any way to collect an error code or anything that might help find out why Photoshop is not loading a plugin.

**Comment by kmoser** [comment]
Thanks, it worked when I placed it this directory:

C:\Program Files\Common Files\Adobe\Plug-Ins\CC

The problem seemed to be that I had it in this directory, which *does* work for the AdobeWebM (fnordware) plug-in but not for yours:

C:\Program Files\Adobe\Adobe Photoshop CC 2019\Plug-ins

This plug-in is awesome, thank you! It would be great if you could zoom in/out the preview but it's still quite useful as is.

**Comment by jh20001** [comment]
Lucky kmoser! It still didn't work for me. I even loaded it into every one of the folders in the end and nothing. The few other plugins load just fine that I added as a test. No plugins show as failed to load. No support for the image format unless I move the AdobeWebM 2015 version back in.

**Comment by y-guyon** [comment]
A few leads you might want to try, although probably pointless:

- Remove all plugins from all Photoshop folders and paste WebPShop.8bi only once to make sure there is no conflict with itself or another plugin,
- Verify again that the architecture (x64) matches the Photoshop installation and the OS,
- Check the content of the [amt3.log file](https://helpx.adobe.com/creative-cloud/kb/troubleshoot-launch-errors-using-logs.html) in case it contains anything relevant,
- Inspect the content of the ZXP archive created by the [Log Collector](https://helpx.adobe.com/creative-cloud/kb/cc-log-collector.html),
- Reboot, reinstall Photoshop, start with a fresh Windows etc.

What are your Photoshop and Windows versions exactly?

**Comment by jh20001** [comment]
Removed all plugins: done. WebPShop.8bi placed into one folder at a time again: done. 64bit, all yes (Win 10). Photoshop ver: 21.1.3. The amt3.log file didn't have any mention of words like error, problem, fail, trouble, and no mention of plugin name. I got that far until I saw the reinstall PS, reinstall Windows. At that point, I gave up as I didn't need it that bad. I'd rather use the other plugin and have basic functionality with than format than wipe everything clean. :/

**Comment by helpdata** [comment]
Same error. My PS version is 20.0.6 20190724.r.80  and  x64. Plugin does not work in PS's plugin folder, nor in the common/adobe/plugins folder. The WebP plugin from Telegraphics.com.au does work, but it's horrible so I want to use this one.

I suspect Adobe has changed the rules for how plugins need to be formatted, and you need to find out about it an rejig your plugin.
https://helpx.adobe.com/photoshop/kb/plug-ins-photoshop-troubleshooting.html

**Comment by borlafdev** [comment]
Same here! 

Windows 10 and Photoshop 2020, tried on all folder locations (not at the same time), and the log seems to say nothing about plugin load error or something like that...

I've succesfully set up on other photoshop versions without any problem.

Thanks in advance.

**Comment by y-guyon** [comment]
I just tried with a fresh Adobe Photoshop 2020 x64 installation (version 21.1.3) on Windows 10 Pro and WebPShop 0.3.0 worked.

Are you even unable to see the "WebP" entry in the "Help > About Plug-In" submenu?

> I've succesfully set up on other photoshop versions without any problem.

May I know whether it was on the same computer and which versions?

**Comment by kevinmcgillivray** [comment]
I had this same issue but found a solution that worked for me (PS 2020, Windows 10 x64).  

When I copy the file directly from the zip file to any of the plugins folders, my computer prompts me that it requires administrative approval to copy the file.  I affirmed the action.  But while trying to diagnose the issue, I noticed that the file was 0K in size.  

So I deleted the file and extracted the zip to my desktop. But for some unknown reason, Norton Antivirus felt the file contained a threat and wouldn't let me extract it.  

I disabled Norton Antivirus, extracted the zip to my desktop, copied the plugin into C:\Program Files\Common Files\Adobe\Plug-Ins\CC\File Formats and launched Photoshop.  This time Photoshop opened and the plugin was active.

**Comment by corentin-gautier** [comment]
@y-guyon same issue for me : windows 10 pro 64 with photoshop 21.1.3. It shows up in "Help > about plug-in" but nothing in the "save as" window

**Comment by y-guyon** [comment]
@corentin-gautier Do you use the default settings for saving? I remember some parameters are unhandled by WebPShop such as another color mode than regular RGB, too big image dimensions etc. that might hide it from the "Save As" menu.
Are you able to open a WebP image downloaded from the Internet with Photoshop? If so, are you able to save it? [This one](https://www.gstatic.com/webp/gallery/4.sm.webp) for example.

**Comment by corentin-gautier** [comment]
@y-guyon oh ok my  image is indeed too big apparently (it's 1500 * 22500)

**Comment by y-guyon** [comment]
From the [FAQ](https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be):

> The maximum pixel dimensions of a WebP image is 16383 x 16383.

**Comment by Edelplastic** [comment]
The Plugin not working. I copied it in every here shown folder and Photoshop not even recognize that Plugin.

**Comment by y-guyon** [comment]
Did you try all of the [troubleshooting steps](https://github.com/webmproject/WebPShop#troubleshooting)? Which OS and Photoshop version are you using?

**Comment by justrealmilk** [comment]
Make sure you're using the right mode and number of bits

![image](https://user-images.githubusercontent.com/156681/101730704-5cf0d500-3a6f-11eb-89c9-78a5aaa40b74.png)
