### ISSUE TITLE
PS 2020 Mac issue with the message 'malicious software'

### ISSUE THREAD

**Issue by daydeer** [webmproject/WebPShop#14]
Hi there! 
First of all, thanks for making this amazing software. 
I've installed the Mac 64bit version and tried it in my PS 2020.
At the first time, it worked well, but after that from the second time suddenly it disappeared in Save file types.
My PS showed this message and also I attached the captured images, please have a look and let me know if there is anyway to figure this out

**“WebPShop.plugin” can’t be opened because Apple cannot check it for malicious software.**

Many thanks 

<img width="416" alt="Screenshot 2020-08-01 at 18 59 18" src="https://user-images.githubusercontent.com/69086144/89107522-7df24b00-d429-11ea-9184-a3998577af67.png">
<img width="415" alt="Screenshot 2020-08-01 at 18 58 55" src="https://user-images.githubusercontent.com/69086144/89107524-7f237800-d429-11ea-94ef-9d21d64c190a.png">

**Comment by y-guyon** [comment]
Thank you for this detailed report.
Have you already tried the `sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2020/Plug-ins/WebPShop.plugin` command? Are you also unable to open WebP files or is it just saving that fails?

**Comment by y-guyon** [comment]
See also https://support.apple.com/guide/mac-help/app-opened-apple-check-malicious-software-mchleab3a043/mac

**Comment by wonsup** [comment]
I had a same issue on the Photoshop 2021 on a Mac, and the above command line workaround solved the issue for me. thanks. (I had to change the command to say 2021 instead of 2020...)

**Comment by yukihirokawauchiya** [comment]
> I had a same issue on the Photoshop 2021 on a Mac, and the above command line workaround solved the issue for me. thanks. (I had to change the command to say 2021 instead of 2020...)

sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin

**Comment by abstractic** [comment]
I also had the same issue, but my save WebP image option is randomly disappearing from the save dialog? 

Anyone who knows how to get it back 🙄

![save-as-dialog](https://user-images.githubusercontent.com/2080809/126583373-5666d0d8-eb8d-4a2a-804c-270c75c33ce8.png)
![save-copy-dialog](https://user-images.githubusercontent.com/2080809/126583375-f0b3d70e-1ae2-472c-8a41-b54b545e4802.png)

**Comment by abstractic** [comment]
Oh, I just discovered it only works with JPEG images and not PNG, is that correct and when did that change, and why?

![save-dialog](https://user-images.githubusercontent.com/2080809/126583796-0fa6daff-1ea9-447a-b7f3-09c025b023a4.png)

**Comment by y-guyon** [comment]
You mean when you open a JPEG image and try to save it as WebP it works, whereas opening a PNG image hides the WebPShop Save As entry? Could you provide the source images for easier reproduction?

The first reason that comes to mind is that the PNG you opened has a color mode, channel depth or dimension that is incompatible. See the [WebPShop limitations](https://github.com/webmproject/WebPShop#limitations).

**Comment by abstractic** [comment]
Okay @y-guyon, I did a bit investigation and it turns out that standard PNG works fine, but PNG smushed with TinyPNG do not work for some reason. I suspect because they are in Indexed color when compressed.

![WebP and Indexed Colors](https://user-images.githubusercontent.com/2080809/126732023-adcabe2d-56cb-4add-984a-c124a96bde9f.png)

**Comment by y-guyon** [comment]
You can convert to Image > Mode > RGB Color before saving as WebP.

**Comment by jzern** [comment]
How much control do you have on this screen? Would you be able to leave WebPShop enabled and then add some error text with detail describing that the format wasn't supported?

**Comment by abstractic** [comment]
Sure @y-guyon, I am not worried on what to do now. I understand the issues and it is clear to me that an inverted coloured image is not supported at this moment. I was just a bit lost earlier, when the menu was there one time and not the next 😄

**Comment by y-guyon** [comment]
@jzern Yes we discussed that solution once already. I will take a look whether Photoshop provides a portable way of signaling a plugin error or if the prompt must be implemented both with win32 and cocoa.

**Comment by imgaryshap** [comment]
Hi All, I'm running Photoshop v2022 (23.0.2) on a MacBook Pro 2019 (16-in) running Monterey 12.0.1.  I am NOT a programmer. Never use Terminal. I cannot get this plugin (and I'm using v0.4.0).  The older version use to work on older versions of Photoshop.  No longer.  I'm getting the same "malicious software" error that others have experienced.  It takes 4 or 5 tries to click out of it.  Can someone tell this programming noob EXACTLY where to drop this plug-in and explain how to enter the code above like I were a 5 year old?   Much appreciated and thank you in advance for the help!

**Comment by y-guyon** [comment]
@imgaryshap 

I am assuming you already have the correct .plugin folder in `Applications/Adobe Photoshop 2022/Plug-ins/`.

Method 1: _"grant an exception for a blocked app by clicking the Open Anyway button in the General pane of Security & Privacy preferences. This button is available for about an hour after you try to open the app"_ from the [macOS user guide](https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac). So when you see the "malicious software" prompt, you should be able to allow it in the General pane of Security & Privacy preferences, for it to work the next times.

Method 2: Copy the following `sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2022/Plug-ins/WebPShop.plugin`, open the Terminal in Finder > Applications > Utilities, use Edit > Paste and finally press Enter. This is taken from the [installation instructions](https://github.com/webmproject/WebPShop#installation).
