### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by janaib** [webmproject/WebPShop#15]
Hello! Thank you for all your work on this plugin. 

I have installed the plugin, but I keep getting this error if I try to save an image as a webp, open a webp image, or inspect the plugin through Photoshop.
<img width="430" alt="Screen Shot 2020-08-06 at 8 42 14 AM" src="https://user-images.githubusercontent.com/69312550/89543355-6bc83200-d7c6-11ea-990e-4da8b5227dfd.png">

I have updated and restarted my photoshop to the newest CC license. I am on a mac version 10.13.6, I ran through the troubleshooting tips, which included trying different file locations, running the permissions command, and restarting my computer, but that didn't fix the error. My coworkers were able to load it fine, so I am sure it is just user error, but I am at a loss of how to move forward.

**Comment by janaib** [comment]
Resolved!! For some reason the WebPShop_0_3_0_Mac_x64 version didn't want to work, but when I used WebPShop_0_2_1_Mac_x64 it worked just fine.

**Comment by janaib** [comment]
Resolved!! For some reason the WebPShop_0_3_0_Mac_x64 version didn't want to work, but when I used WebPShop_0_2_1_Mac_x64 it worked just fine.

**Comment by y-guyon** [comment]
Thank you for the detailed report and for posting a workaround. I suggest comparing the plugin, Photoshop and MacOS versions and installation directories with your coworkers to find a potential cause.

Unfortunately I cannot reproduce the issue.

**Comment by MrMerkin** [comment]
I just wanted to comment here in case anyone runs into this again. On my old Macbook Pro retina laptop running Mojave 10.14.2, I also got this same error in Photoshop 2020 and 2021. Using the same WebPShop_0_2_1_Mac_x64 release as @janaib, it now works fine. New plug-in version apparently doesn't always play nice with old macOS. Might be hardware related as well. 🤷🏻‍♂️

**Comment by ibaivalencia** [comment]
> I just wanted to comment here in case anyone runs into this again. On my old Macbook Pro retina laptop running Mojave 10.14.2, I also got this same error in Photoshop 2020 and 2021. Using the same WebPShop_0_2_1_Mac_x64 release as @janaib, it now works fine. New plug-in version apparently doesn't always play nice with old macOS. Might be hardware related as well. 🤷🏻‍♂️

Thanks @MrMerkin , same here. With a 2011 27" iMac and 10.13.6 only works the WebPShop_0_2_1_Mac_x64 release. At least it's working. Thanks!
