### ISSUE TITLE
PS cc 2020 was not finding the files with the path provided

### ISSUE THREAD

**Issue by hjmoore420** [webmproject/WebPShop#18]
I worked through terminal and the command I used was: 

sudo xattr -r -d com.apple.quarantine "/Applications/Adobe Photoshop 2020/Plug-ins/WebPShop-master"

this worked, I loaded PSS and was able to open the files I needed to... thanks so much. I hope this helps someone else.

**Comment by y-guyon** [comment]
Thank you for your feedback.
