### ISSUE TITLE
Getting error when trying to open or save images as webp

### ISSUE THREAD

**Issue by JScott-MSI** [webmproject/WebPShop#20]
Shows up in the Open or Save  as... dialogs but throws this error. PS 2020 21.2.4 OS High Sierra 10.13.6
![webp error](https://user-images.githubusercontent.com/52297130/95488110-015c7b00-094a-11eb-957b-41f83b133d37.jpeg)

**Comment by skal65535** [comment]
Hi,

could you indicate the exact steps to reproduce the problem? Thanks!

**Comment by JScott-MSI** [comment]
Have a jpg or PS file open in PS , go to save as… choose web and click save… 

Nothing extraordinary…

**Comment by JScott-MSI** [comment]
Choose webp not web…

**Comment by y-guyon** [comment]
Did you try all of the [troubleshooting steps](https://github.com/webmproject/WebPShop#troubleshooting)? Did the [`xattr` command](https://github.com/webmproject/WebPShop#installation) print some warning or error? Does the "Help > About Plug-In > WebP" submenu display the same prompt? 

This [thread](https://github.com/webmproject/WebPShop/issues/15) references a similar issue, you might try the version [0.2.1](https://github.com/webmproject/WebPShop/releases/tag/v0.2.1) too just in case.

**Comment by JScott-MSI** [comment]
I did try the troubleshooting, I’m not running macOS 10.15+ so I don’t get the “can’t identify” error,  however I ran the xattr anyway and I did not get an error in terminal. I do get the same error in the About Plugin menu. WebP shows in the menu but it gives the same error.

I tried installing the 0.2.1 version and that works…

I see that there is a .0.3.1 version for Mac but I don’t see a bin for 0.3.1 only 0.3.0 is there a bin available to try the latest version?

**Comment by y-guyon** [comment]
I cannot reproduce the issue so I am unable to fix it for now. I would recommend updating to the latest MacOS/Photoshop version if possible, that might solve the problem (no guarantee though).

Regarding the 0.3.1 version, it mainly contains clean-ups so I doubt it would bring a solution. You can compile it by following [these steps](https://github.com/webmproject/WebPShop#build) if you still want to give it a try.

**Comment by davidkaplan** [comment]
Same issue for me.  PS CC 2019, macOS High Sierra.  Ran the `xattr` command without issue.  Downloaded a webp file, try to open it and get the **`Could not complete your request because the file was not found.`** error message.

System Info:

> `Adobe Photoshop Version: 20.0.10 20200706.r.120 2020/07/06: 1208496  x64`
> `Operating System: Mac OS 10.13.6`
> 
> `Optional and third party plug-ins:`
> `   WebP Copyright 2018-2020 Google LLC - from the file “/Applications/Adobe Photoshop CC 2019/Plug-Ins/WebPShop.plugin/”`
> 
> `Duplicate and Disabled plug-ins: NONE`
> 
> `Plug-ins that failed to load: NONE`
`

**Comment by FemurTG** [comment]
I am having the exact same problem.  PS CC 2020 on mac OS High Sierra.  When I try to open or save webp files it says file not found.

**Comment by y-guyon** [comment]
Thank you for your reports. Unfortunately I am still unable to reproduce the issue. I found [this thread](https://feedback.photoshop.com/conversations/photoshop/photoshop-jpegplugin-causes-could-not-complete-your-request-because-the-file-was-not-found-error/5f5f45c54b561a3d425edd98) that seems similar for another plugin ("JPEG.plugin"), you could try reinstalling Camera Raw as mentioned there if the other leads suggested here do not work.

**Comment by gseppi** [comment]
Having the same issue.  (both versions 0.3 and 0.2 - also updated Camera Raw)
PS CS6 extended | macOS 10.14

Any progress?

**Comment by y-guyon** [comment]
Unfortunately, older versions of Photoshop are not supported. Please see [issue #17](https://github.com/webmproject/WebPShop/issues/17) for more details. You can use [Telegraphics' plug-in](http://www.telegraphics.com.au/sw/product/WebPFormat) as an alternative.

**Comment by gseppi** [comment]
thank you for the reply. 
At least now I know (that also explains why saving for web was only bitmap)- I've been unsuccessful in finding supported versions for this plugin, what is the oldest version this will work with?

Unfortunately, telegraphics' didn't work all that well.

**Comment by y-guyon** [comment]
I only try the latest version of Photoshop at each release. You can find the history [here](https://github.com/webmproject/WebPShop/blob/master/docs/NEWS.md). Photoshop CC 2018 was the first one.

**Comment by e8vww** [comment]
> I only try the latest version of Photoshop at each release. You can find the history [here](https://github.com/webmproject/WebPShop/blob/master/docs/NEWS.md). Photoshop CC 2018 was the first one.

I'm having this problem with CC 2019 (20.0.7)
