### ISSUE TITLE
I'm stupid and can't figure out how to save as an animated webp

### ISSUE THREAD

**Issue by esanscoopsers** [webmproject/WebPShop#22]
each layer is a frame, I've named each layer "123 ms" and rasterized them like the intructions said. It won't give me the options for animated webp, it just gives me the options for an image webp

**Comment by y-guyon** [comment]
Could you try with round brackets? Layer names such as:

- Frame 0 (100 ms)
- Frame 1 (100 ms)
- Frame 2 (100 ms)

Alternatively, [this WebP animation](https://i.ibb.co/Fb5TXn5/anim.webp) should load correctly in Photoshop with WebPShop and should display the animated options when saved as WebP, and could be used as a reference.

**Comment by JoelEadeDesign** [comment]
Same here @esanscoopsers .  Tried with an MP4 and Animated GIF in Photoshop but I don't see the Animated WebP option either.

**Comment by y-guyon** [comment]
From the ["Limitations" section](https://github.com/webmproject/WebPShop#limitations):

> The Timeline data is not used

[This post](https://community.adobe.com/t5/photoshop-ecosystem-discussions/retrieving-animation-timeline-data-in-photoshop-cs3/m-p/3398652) mentions the impossibility of a format plug-in such as WebPShop to access Photoshop animation frames. That is why the animations you open with Photoshop (MP4, GIF) cannot be converted to WebP without manually renaming the layers, and animated WebP cannot be converted to other formats without manually entering the Timeline data. I would suggest Gimp, an online converter or a local tool to do these conversions.

Could you try what is described in [comment 2](https://github.com/webmproject/WebPShop/issues/22#issuecomment-720976664)?
