### ISSUE TITLE
PS CC2019 Can't save ou export PSD to webp.

### ISSUE THREAD

**Issue by noritaka97** [webmproject/WebPShop#23]
When i try to save PSD to webp, webp format is not present.
![image](https://user-images.githubusercontent.com/64798635/98183596-dc264280-1ede-11eb-8943-42d62295af0a.png)

i can open but not save webp format.
![image](https://user-images.githubusercontent.com/64798635/98183819-5f479880-1edf-11eb-8b91-b820091a0188.png)

**Comment by y-guyon** [comment]
What is the MacOS version? Can you save as WebP an image that you opened from a WebP file ([this one](https://github.com/webmproject/WebPShop/raw/master/docs/webpshop_enc_ui_windows.webp) for example)? My first guess would be unsupported settings (color mode etc.).

**Comment by noritaka97** [comment]
Hi Y-Guyon,

MacOs : Catalina 10.15.7
yes i can open it and now i have webp save as option...
![image](https://user-images.githubusercontent.com/64798635/98235611-6e0e6980-1f38-11eb-939d-29f374ff4f65.png)

an unsupported setting in the PS preference ou in the psd files ?

**Comment by y-guyon** [comment]
See the [constraints](https://github.com/webmproject/WebPShop#limitations) of WebPShop. This is likely related to the canvas size or image mode.

**Comment by noritaka97** [comment]
Thank's for your help @y-guyon , i found the problem, the plugin work only with 8 bits pictures.

**Comment by thenewguy** [comment]
Same issue on latest CC.  It would be ideal if the image didn't meet the constraints mentioned by @y-guyon if the image was automatically modified to meet these requirements.  Right now the workflow for transparent images is to export as PNG and then convert to webp.  It works but the extra steps slow down the process

**Comment by y-guyon** [comment]
I agree. WebP constraints are specified in the [resource file of WebPShop](https://github.com/webmproject/WebPShop/blob/master/common/WebPShop.r#L73). Unfortunately Photoshop just removes the export option instead of offering a conversion to a supported image mode.
