### ISSUE TITLE
Photoshop script for WebP

### ISSUE THREAD

**Issue by bmustata** [webmproject/WebPShop#25]
Can we use this with a photoshop script?

Similar... 🎩 
```
// our web export options
var options = new ExportOptionsSaveForWeb();
options.quality = 70;
options.format = SaveDocumentType.JPEG;
options.optimized = true;

var newName = 'web-'+doc.name+'.jpg';

doc.exportDocument(File(newName),ExportType.SAVEFORWEB,options);
```

**Comment by y-guyon** [comment]
I implemented automation support in [WebPShopScripting.cpp](https://github.com/webmproject/WebPShop/blob/master/common/WebPShopScripting.cpp). Available keys can be found in [WebPShop.r](https://github.com/webmproject/WebPShop/blob/master/common/WebPShop.r#L156). I did not test Photoshop scripts but hopefully they share the same implementation as the Actions.

**Comment by bmustata** [comment]
<pre>
function save_as_webp(doc, toFilename) {
    try {
        var idsave = charIDToTypeID('save')
        var desc10 = new ActionDescriptor()
        var idAs = charIDToTypeID('As  ')
        var desc11 = new ActionDescriptor()
        var idwrtq = charIDToTypeID('wrtq') // quality
        desc11.putInteger(idwrtq, 80)
        var idwrtc = charIDToTypeID('wrtc') // compression
        desc11.putInteger(idwrtc, 1)
        var idwrte = charIDToTypeID('wrte') // keep_exif
        desc11.putBoolean(idwrte, false)
        var idwrtx = charIDToTypeID('wrtx') // keep_xmp
        desc11.putBoolean(idwrtx, false)
        var idwrtp = charIDToTypeID('wrtp') // keep_color_profile
        desc11.putBoolean(idwrtp, false)
        var idwrtl = charIDToTypeID('wrtl') // loop_forever
        desc11.putBoolean(idwrtl, true)
        var idGoogleWebPShop = stringIDToTypeID('Google WebPShop')
        desc10.putObject(idAs, idGoogleWebPShop, desc11)

        var idIn = charIDToTypeID('In  ')
        desc10.putPath(idIn, new File(toFilename))
        var idDocI = charIDToTypeID('DocI')
        desc10.putInteger(idDocI, 195)
        var idCpy = charIDToTypeID('Cpy ')
        desc10.putBoolean(idCpy, true)
        var idLwCs = charIDToTypeID('LwCs')
        desc10.putBoolean(idLwCs, true)
        var idsaveStage = stringIDToTypeID('saveStage')
        var idsaveStageType = stringIDToTypeID('saveStageType')
        var idsaveSucceeded = stringIDToTypeID('saveSucceeded')
        desc10.putEnumerated(idsaveStage, idsaveStageType, idsaveSucceeded)

        executeAction(idsave, desc10, DialogModes.NO)
    } catch (e) {
        alert('exp ' + e)
    }
}
</pre>

and tks guys for this great plugin.

**Comment by y-guyon** [comment]
Thank you for sharing your script!
