### ISSUE TITLE
WebP plugin doesn't work in M1-updated Photoshop

### ISSUE THREAD

**Issue by cpedraza-ca** [webmproject/WebPShop#27]
I followed the instructions for installing the WebP plugin. It is in the plugin folder of Photoshop on my M1 Mac mini. I ran the terminal command you suggested. 

Though the plugin is in the correct folder, it does not show up in the About > Plugins menu. Only Camera Raw does.

I attempted to install the day after the Photoshop update for M1 Macs was released. I assume the plugin isn't compatible with the newly updated version?
![Applications](https://user-images.githubusercontent.com/18127373/110852508-50933880-8267-11eb-8d04-82c8af78e1e0.jpg)

**Comment by y-guyon** [comment]
May I know which command you ran? The one described in the [README.md](https://github.com/webmproject/WebPShop#installation) was for Photoshop 2020, so you may need to replace "2020" by "2021":
```
sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin
```
Also it might help to know the exact Photoshop version.

**Comment by choegl** [comment]
The plugin is not working natively on Apple M1 silicon yet, it seems. If you open the Photoshop info with Command+I and tick the "open with Rosetta" checkbox it works. Let's hope there will be a universal binary or Apple version soon…

**Comment by leewolz** [comment]
@choegl - that worked for me, thanks!

**Comment by electrikmilk** [comment]
If all you're needing WebPShop for is to convert it to a JPEG or PNG, I found that Apple's Preview app will recognize the WebP format and allow you to convert it to a JPEG or PNG by converting it to a TIFF.

**Comment by laurentho** [comment]
> The plugin is not working natively on Apple M1 silicon yet, it seems. If you open the Photoshop info with Command+I and tick the "open with Rosetta" checkbox it works. Let's hope there will be a universal binary or Apple version soon…

The latest 22.3 version with native M1 support doesn't have the checkbox for opening with Rosetta anymore.

**Comment by miwucs** [comment]
We've added a candidate "universal" build with M1 support on the latest release  https://github.com/webmproject/WebPShop/releases/tag/v0.3.3
Could you try it and let me know if it works?

**Comment by choegl** [comment]
Just tested it. Works like a charm! (once I was able to get around the pesky Apple safe keeper and allowing access to the plugin file in the system settings security section)

**Comment by miwucs** [comment]
Thank you, glad to know it works! I'm closing the issue then.
