### ISSUE TITLE
[Windows] PS 2021 crashes upon loading WebP in MS RDP session

### ISSUE THREAD

**Issue by akuropka** [webmproject/WebPShop#28]
Environment:
Windows 10.0.19041.906 x64
Photoshop 22.3.0.49 x64
WebPShop 0.3.2
MS-RDP session

Upon trying to load a WebP-Picture Photoshop crashes and creates the attached report. No crash happens during local session.

[crashreport.xml.txt](https://github.com/webmproject/WebPShop/files/6250393/crashreport.xml.txt)

**Comment by y-guyon** [comment]
Thanks for your report. Unfortunately I am unable to reproduce the issue. It works fine on my Google Cloud remote session, but this is an online instance, maybe there is a graphics software explanation in your case. I did not find any clue in the crash report: nothing is related to the plugin in the dumped stack trace. Does it happen only with WebPShop?

**Comment by akuropka** [comment]
I guess it's related to the MS RDP graphics interface and only happens with webp files.
Anyways, it's nothing too important (e.g. VNC works as well).
Thanks for your attention!
