### ISSUE TITLE
Version 0.3.3 WebShop plugin doesn't work on MAC

### ISSUE THREAD

**Issue by mraymond-design** [webmproject/WebPShop#29]
Anyone know when the most recent version of this plugin will work on MAC ? Thanks !

**Comment by y-guyon** [comment]
I am currently working on building a Universal macOS Binary of WebPShop, so I hope soon, sorry for the delay. No guarantee though.

**Comment by mraymond-design** [comment]
Thank you !

**Comment by miwucs** [comment]
A universal binary is now available https://github.com/webmproject/WebPShop/releases/tag/v0.3.3
