### ISSUE TITLE
Mac OS 10.15 - doesn't work

### ISSUE THREAD

**Issue by digitalsmithy** [webmproject/WebPShop#3]
“WebPShop.plugin” cannot be opened because the developer cannot be verified.

**Comment by digitalsmithy** [comment]
Workaround: Remove quarantine flag.
TERMINAL
sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2020/Plug-ins/WebPShop.plugin

**Comment by y-guyon** [comment]
Do you get this error when running Photoshop or at another step?
Do you have the same issue when getting the binary through git and/or building it yourself?
Thank you for the workaround.

**Comment by digitalsmithy** [comment]
Copy plugin to plugin folder. Start PS. Open any WebP file. You get the error, because the plugin is not 'from an official developer' - and plugins are now included in the 'protected folders' for Mac OS X.
It will then report 'File not found' - but in fact it's because it's rejected the plugin.

**Comment by meoutlook** [comment]
> Workaround: Remove quarantine flag use this variant to Photoshop 2021.
> TERMINAL
sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin
