### ISSUE TITLE
Universal Mac not Working

### ISSUE THREAD

**Issue by justinthejaguar** [webmproject/WebPShop#30]
It appears that the plugin has stopped working on my intel mac. The option to save as a webp no longer appears. I attempted deleting the existing plugin and using a fresh version.

**Comment by y-guyon** [comment]
Thanks for the report. Could you provide the MacOS, Photoshop and WebPShop versions, both the working and failing ones?

**Comment by y-guyon** [comment]
This is odd. Based on the [Troubleshooting steps](https://github.com/webmproject/WebPShop#troubleshooting):
- Are you able to see the plugin listed in the "About Plug-In" menu?
- In which folder(s) did you copy the plugin?
- Did you successfully run the [`xattr` command](https://github.com/webmproject/WebPShop#installation)?
- Are earlier versions of WebPShop working better, such as the [0.3.2](https://github.com/webmproject/WebPShop/releases/tag/v0.3.2)?

**Comment by y-guyon** [comment]
Good to hear that it works. I recently tried to fix the name appearing in the "About Plug-In" to be "WebPShop" instead of just "WebP" but I guess it also changed it in the "Save As" prompt.
