### ISSUE TITLE
Terminal Command Line crashes Photoshop 2021

### ISSUE THREAD

**Issue by JoeDesigner68** [webmproject/WebPShop#31]
After entering the command line “sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin” Photoshop will not launch.

**Comment by y-guyon** [comment]
Thanks for the report. Could you provide the MacOS, Photoshop and WebPShop versions? The command line output might prove informative too.

**Comment by JoeDesigner68** [comment]
macOS 10.15.7

Photoshop 22.3.1

When I ran "sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2020/Plug-ins/WebPShop.plugin"

I got: "no such file"

So I changed the command to: "sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin"

Here’s the log:

> The default interactive shell is now zsh.
> To update your account to use zsh, please run `chsh -s /bin/zsh`.
> For more details, please visit https://support.apple.com/kb/HT208050.
> Joes-iMac-2:~ jofus$ sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2020/Plug-ins/WebPShop.plugin
> Password:
> xattr: No such file: /Applications/Adobe Photoshop 2020/Plug-ins/WebPShop.plugin
> Joes-iMac-2:~ jofus$ sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin
> xattr: No such file: /Applications/Adobe Photoshop 2021/Plug-ins/WebPShop.plugin
> Joes-iMac-2:~ jofus$ sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin
> Joes-iMac-2:~ jofus$ 

```

**Comment by y-guyon** [comment]
I see you have an occurrence of `xattr: No such file: /Applications/Adobe Photoshop 2021/Plug-ins/WebPShop.plugin` too but I guess you solved it somehow.

If the issue of not being able to open Photoshop comes from WebPShop, deleting the plug-in should solve it. Also did you try to restart your iMac by any chance?

**Comment by y-guyon** [comment]
You may also try the [version 0.3.3 of WebPShop](https://github.com/webmproject/WebPShop/releases/tag/v0.3.3) instead of the 0.3.2.

**Comment by y-guyon** [comment]
I changed the README.md with up-to-date instructions and direct links.

**Comment by JoeDesigner68** [comment]
Thanks for your responses. However, photoshop continues to crash on load.  I’m really in a jam now. I use photoshop everyday and nothing seems to work. 

- I deleted the plugin
- I restarted my computer
- I re-installed photoshop

Is there any way to purge that command line or reverse it?

<img width="545" alt="Screen Shot 2021-04-29 at 10 29 54 AM" src="https://user-images.githubusercontent.com/83414435/116578429-03325f80-a8d7-11eb-9f54-5682d4676004.png">

**Comment by y-guyon** [comment]
I guess the opposite of
```
sudo xattr -r -d com.apple.quarantine /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin
```
would be
```
sudo xattr -r -w com.apple.quarantine [ATTR_VALUE] /Applications/Adobe\ Photoshop\ 2021/Plug-ins/WebPShop.plugin
```
with `[ATTR_VALUE]` being the result of
```
sudo xattr -r -p com.apple.quarantine /Downloads/WebPShop.plugin
```
done on a freshly downloaded and extracted WebPShop binary.

However I doubt this would solve anything if deleting the plug-in file did not work. I have no clue on how trying a plug-in once could crash Photoshop permanently, it makes no sense. Did you try to look into the report mentioned in the prompt? Maybe reinstalling Photoshop is not enough, you may have to manually remove any installation leftover. I would suggest looking for help in Adobe resources (forum, online doc).

**Comment by bmercernccer** [comment]
Whenever Photoshop crashes on launch one of the first things I try is throwing away the preferences. Crashing can cause corrupted preferences files, and those can then cause further crashes.
