### ISSUE TITLE
Convert tiff/psd to WebP

### ISSUE THREAD

**Issue by bjuanma** [webmproject/WebPShop#33]
Can tiff or psd files be converted to WebP with Photoshop plugin or some other tool on mac os x?

**Comment by y-guyon** [comment]
Yes, you can use Photoshop and WebPShop to convert TIFF or PSD files to WebP images. [GIMP](https://www.gimp.org/) should be able to do that for TIFF as well.

The [cwebp](https://developers.google.com/speed/webp/docs/cwebp) command line tool is also an option, as well as [ImageMagick](https://imagemagick.org/) and online converters.
