### ISSUE TITLE
Unknown issue

### ISSUE THREAD

**Issue by UltimatumMCCX** [webmproject/WebPShop#35]
Hi, I have recently install latest version of PS 2021(22.3.1) and copy the plugin to plugin folder as usual
But now I'm having issue with the images and I'm not able to edit/make change of it. The transparency has gone or having weird colors/texture. However when I opened the images in chrome or other image viewers, it seem fine. 
I have tried re-install PS but its not working. It's working fine in previous version.

Here's what it look like.
![image](https://user-images.githubusercontent.com/86172952/122658149-62f10c80-d19c-11eb-902d-a5d759f9500b.png)
It should be image of crosshair and having transparent background.

Image are working fine in the program or view in other apps. ignore the white background as I'm open it in chrome.
![image](https://user-images.githubusercontent.com/86172952/122658187-e3177200-d19c-11eb-89cd-128d710a2909.png)

**Comment by y-guyon** [comment]
Thank you for your report.

Could you provide a few more details:
- Your operating system version
- The problematic source image
- The exact steps to reproduce the issue

On my side, with Photoshop 22.4.2 Release and WebPShop 0.3.3 on Windows Server 2016, creating a 210x150 px transparent image, saving it as WebP and opening it, no problem occurs.
