### ISSUE TITLE
RC1015 cannot open include file'WebPShop.pipl'.

### ISSUE THREAD

**Issue by mannokage** [webmproject/WebPShop#37]
Hi!
     RC1015 cannot open include file'WebPShop.pipl'.
This error occurred when I was refactoring the source code with visual studio. I couldn't solve this problem.

**Comment by y-guyon** [comment]
Does the project build at head without your refactoring?

If so, you could try:
- Comparing file trees and VS project config files of WebPShop at head and your changes, with a diffing tool (such as Meld), to find where the issue might come from,
- Start over and refactor one small step at a time, building each time, to find the culprit.
