### ISSUE TITLE
WebP save options not coming up for 16 & 32bit photoshop projects

### ISSUE THREAD

**Issue by Itamiii** [webmproject/WebPShop#38]
In Photoshop v 22.4.3 (latest stable release at this date) the webp save as option is not coming up for me.
Edit: I managed to identify this to be caused by the project bit depth setting.
For 8bit projects (which I never work in) everything works as intended.
In 16 & 32bit mode, there is no more option to save as WebP.

I don't know since when this is happening since I have not used to plugin in a while, but I could really use a fix.

If the way how to save files has changed since I last used the plugin, I apologize. I could not find any indication of this being the case.

**Comment by y-guyon** [comment]
Photoshop may have recently restricted the formats available in the **Save As...** menu when there are several layers, I am not sure why.

Are you able to open a WebP file?\
Does it work when using the **Save a Copy...** menu?

**Comment by Meliina** [comment]
Just noticed the same issue when trying to save a new project as webp.
I hope someone finds a fix for this.

**Comment by Itamiii** [comment]
I figured out what's causing this (or so I believe).

The document bit depth seems to be the issue. 
In a 8bit project on the latest photoshop build, everything works and the save options come up as intended. 
However, as soon as it's a 16 or 32bit project, the WebP save options are no longer available.

As I only work in 16bit, I believe this used to work awhile ago in previous versions.
Either way, if WebP save options could be made available in 16bit mode as well, I would be very grateful - as it would make my work tremendously much faster.

Thanks for your work and time.

**Comment by A20N** [comment]
Unfortunately, I have the same issue but also in RGB & 8Bit mode.
I can open WebP images and save them, but when I try to save a jpg as WebP, I no longer have the option to select WebP - just like OP.

**Comment by y-guyon** [comment]
This should be fixed by [WebPShop v0.4.0](https://github.com/webmproject/WebPShop/releases/tag/v0.4.0).

**Comment by sylicongames** [comment]
I know this is closed, but  ive not been able to save-as or export .WEBP in 16bit or 32bit. Every setting and workflow I try ends un in 8 bit. Tried all versions of Adobe PS from 21x forward to todays 23.2.x Any ideas?

**Comment by y-guyon** [comment]
See issue #44.
