### ISSUE TITLE
Photoshop cannot save as webp files if in CMYK color mode

### ISSUE THREAD

**Issue by caominhsg** [webmproject/WebPShop#40]
Hi,
If Photoshop in CMYK color mode, its cannot be save as WebPShop files but when I switch to RGB color mode is can be. 

Is it plugin problem or default option of  WebPShop plugins?

I'm using Photoshop version 22.0.5

**Comment by y-guyon** [comment]
Thank you for your enquiry. As written [here](https://github.com/webmproject/WebPShop#limitations):

> Only "RGB Color" image mode is currently supported.

I do not plan supporting other color modes as the conversion can be complex. However I am currently rolling out a release handling 16 and 32 bits/channel for RGB.
