### ISSUE TITLE
Maybe a bug...

### ISSUE THREAD

**Issue by WangXu18** [webmproject/WebPShop#43]
first, i opened a document and paint on it.
then,i used `Ctrl+S` and choosed the WebPShop type. 
Well, when i click the 'Save' button opened the WebPShop dialog. i click the close button which located at WebPShop dialog's top-right.
the Photoshop.exe losed any response.

**Comment by WangXu18** [comment]
i mean,maybe you took over some messages from photoshop, but you forgot to release it?

**Comment by WangXu18** [comment]
Windows 10 64, Photoshop 20.0.0 x64

**Comment by y-guyon** [comment]
Thank you for the report.

I am able to partially reproduce the issue on Photoshop 22.5.1 and WebPShop 0.4.0 on Windows Server 2016 Datacenter x64:
I get a different behavior between the "Cancel" and "X" buttons. The latter produces a weird Photoshop window focus loss, where I am unable to click on anything until I get the Windows focus back to Photoshop by clicking on the taskbar. However Photoshop is still responsive after that, so it might not be the same issue as yours.

**Comment by y-guyon** [comment]
I released [WebPShop 0.4.1](https://github.com/webmproject/WebPShop/releases/tag/v0.4.1). Could you check that it fixes your issue? The weird focus shift is gone on my side.

**Comment by WangXu18** [comment]
ok

**Comment by WangXu18** [comment]
i tested this new version, and the previously described problem no longer recurs.
