### ISSUE TITLE
Opening "About Webp" in the Help > About Plugins menu cannot be closed and PS process must be aborted to escape

### ISSUE THREAD

**Issue by hjhopp** [webmproject/WebPShop#45]
There is no X to click nor escape button functionality. UI is completely blocked by this help window.

I am using Windows 10 19042.1165, Photoshop 2020 21.2.4, Webp plugin 0.3.3.

**Comment by y-guyon** [comment]
Thanks for your report. I know this is not obvious, but have you tried clicking the window content itself?

I may add a "click here to exit" sentence in the box (because clicking anywhere on the text closes it) or take more time to see how to add an X button in WIN32 UI.

**Comment by hjhopp** [comment]
Hi, I tried doing what you said, and that worked!

**Comment by y-guyon** [comment]
Fixed in [WebPShop v0.4.2](https://github.com/webmproject/WebPShop/releases/tag/v0.4.2).
