### ISSUE TITLE
Images dragged in from another tap in photoshop removes the save as webp option in photoshop.

### ISSUE THREAD

**Issue by TheRealArtonn** [webmproject/WebPShop#46]
I've been scratching my head for a while, but for some reason if i drag an image into another tap in photoshop the webp save as option is removed. I can save as the image itself in it's own respectable tap but as soon as i move it over to a freshly made canvas the save as webp option disappears.

Until i remove the dragged over image, it won't export in webp. 

When i say dragged over, imagine having 4 images open in 4 different taps in photoshop. Then taking one image clicking on it and simply dragging it over to one of the other existing taps now having two images in the same tap.

**Comment by y-guyon** [comment]
Thank you for the report. Do you mean dragging in from another "tab"?

I did not try to reproduce the issue yet, but I have a [lead](https://github.com/webmproject/WebPShop/issues/38#issuecomment-892829727): try the **Save a Copy...** menu.
