### ISSUE TITLE
Photoshop 2022 doesn't recognize plugin

### ISSUE THREAD

**Issue by laurenbc** [webmproject/WebPShop#47]
I cannot get this plugin working no matter what folder/path I put it in. I'm using Photoshop CC 2022, any suggestions?

**Comment by y-guyon** [comment]
Thanks for your report. I guess you already tried all [troubleshooting steps](https://github.com/webmproject/WebPShop#troubleshooting)?

Which WebPShop version are you using, and on what operating system? \
Could you describe what file you copied and where, exactly?

**Comment by whalehub** [comment]
@laurenbc The good news is that Adobe finally added official support for WebP to Photoshop version 23.2: https://helpx.adobe.com/photoshop/using/whats-new/2022-1.html#support-for-webp

**Comment by whalehub** [comment]
@laurenbc The good news is that Adobe finally added official support for WebP to Photoshop in version 23.2: https://helpx.adobe.com/photoshop/using/whats-new/2022-1.html#support-for-webp
