### ISSUE TITLE
How to mark end frame in WebP animation?

### ISSUE THREAD

**Issue by vladrozhnev** [webmproject/WebPShop#5]
Hello. How to mark end frame in WebP animation? If I want the one time animation only - how can I mark the last frame? Because currently I am use something like 9999999ms and it works, but it's not so fine.

**Comment by y-guyon** [comment]
WebPShop does not yet support setting the Loop Count parameter. Here are some options:

- Use the [Gnu Image Manipulation Program (GIMP)](https://www.gimp.org/) to export the file as a WebP image and untick the "Loop forever" setting in the "Animation" category,
- Open the WebP file with an hex editor, find the ["ANIM" chunk](https://developers.google.com/speed/webp/docs/riff_container#animation) and replace the 13th byte by 0x01 and the 14th byte by 0x00 (little endian). By example, replace the last two bytes of `41 4E 49 4D 06 00 00 00 FF FF FF FF 00 00` by `01 00`.

**Comment by y-guyon** [comment]
Fixed in e5e16782b87ac90d690361251d900187d9e52d3e.
