### ISSUE TITLE
Photoshop reports program error on saving

### ISSUE THREAD

**Issue by Galanos** [webmproject/WebPShop#52]
First, thank you for the plugin.

I tried using it in Photoshop 12.1 (Creative **Suite** 5.5) on OS X 10.14.6 (Mojave). It loads correctly and appears in “Photoshop > About Plugins”. The file format option “WebPShop” is selectable in the “Save as…” dialogue and the image settings are displayed in the next step, options are selectable, preview is rendered correctly, everything looking great.

But on confirming the image settings Photoshop reports a program error and doesn’t save the image—see attached screenshot. The German text translates to _“The file could not be saved as “test.webp” because a program error occured.”_

<img width="547" alt="Bildschirmfoto 2022-06-28 um 12 47 04" src="https://user-images.githubusercontent.com/2743446/176162044-4c36ed24-649f-4161-9dd0-e91b5a8659f2.png">

I know PS CS 5.5 is really, really old and probably not supported by you (I wasn’t able to find any compatibility tables here on GitHub) but I’m hoping that there’s a simple solution you can recommend. I can’t update from Mojave because Catalina doesn’t support the Creative Suite.

Thank you!

**Comment by y-guyon** [comment]
Unfortunately, as specified [here](https://github.com/webmproject/WebPShop#limitations), only the latest Photoshop release is supported.

You can find alternatives in [this post](https://github.com/webmproject/WebPShop/issues/6#issuecomment-720450894).
