### ISSUE TITLE
Plugin returns error on OSX 10.11.6

### ISSUE THREAD

**Issue by schroef** [webmproject/WebPShop#6]
Tried this version of the plugin from the latest releases.

![Screen Shot 2020-03-16 at 16 59 15](https://user-images.githubusercontent.com/6923008/76799205-7f3b1800-67a7-11ea-98b8-a5e045ba989e.png)

**Comment by y-guyon** [comment]
Thanks for your report.
Could you provide the following for easier problem reproduction:
- The image in PNG format to be saved in WebP (or another that produces the same issue if this one cannot be made public),
- The steps taken to Save this image in WebP format (from the opening of the PNG file) and the encoding parameters used.
Does it occur all the time or is it an issue that appears with some images/settings only?

**Comment by DanL12186** [comment]
I get the same thing in 0.21; in 0.30 it fails to save "because the file could not be found".

The only steps to reproduce are installing the plugin, any combination of save or save as with a new or existing image, selecting the WebP format (copy, not a copy, etc makes no difference), and then hitting save.  MacOS 10.11.6, CC 2018.

**Comment by rubin55** [comment]
I just downloaded the WebP plugin, Mac OS X Mojave (10.14.6) with Photoshop CS6; I get the exact same error window, no explanation.

**Comment by y-guyon** [comment]
Updating Photoshop to the latest version should solve the issue (WebPShop does not support older versions). Alternatively disabling any antivirus and/or allowing the plug-in might help in some cases.

Are you able to open a WebP file ([like this one](https://www.gstatic.com/webp/gallery/4.sm.webp)) with Photoshop or it also returns an error?

**Comment by rubin55** [comment]
What a cop-out! There's a huge number of people that will run older versions of Photoshop. CS6 is still considered a standard product (it being the last non-subscription based version and all). As stated, opening works.

I don't particularly care, I just noted that I run into the same issue. Good luck getting your format widely supported I guess.

**Comment by y-guyon** [comment]
I understand and I would like to make it backward-compatible but I did not find a way to buy a Photoshop CS6 license from Adobe, even for development purposes. However contributions to make WebPShop work with CS6 from people owning this version are welcomed.

**Comment by elecenet** [comment]
Hi, I'm having the same error ("file not found") in OS X 10.11 + Photoshop CC 2018.
After installing WebPShop.plugin in the /plugin/ folder, restart, Open... 
![Captura de pantalla 2020-09-15 a las 14 28 33](https://user-images.githubusercontent.com/26528601/93210397-d1adbf00-f75f-11ea-8ffa-66d39ddd2be0.jpg)
Failed to accomplish because file not found.
(File is in desktop and checked OK)
Same thing in Save as.../WebP
But!
Saving as WebP-lossless generates a correct .webp file.

**Comment by y-guyon** [comment]
After which action do you encounter this error (Save, Open, before/after the encoding settings window etc.)? Did you try the [troubleshooting steps](https://github.com/webmproject/WebPShop#troubleshooting), including the `xattr` command? You can also test [older versions](https://github.com/webmproject/WebPShop/releases) of WebPShop, it seemed to work better for others.

**Comment by elecenet** [comment]
System version is 10.11 (top possible for my hardware)
Photoshop is CC 2018 (top possible for OSX 10.11)
This error happens at:
- Opening .webp file
- Saving file as .webp
- Checking about... Webp plugin
Always same message (Failed to accomplish because file not found.)
I executed the xattr command (path adapted to my file paths) but no changes.
Photoshop **recognizes** the plugin, and also in Open... lists the .webp files are recognized (not ghosted)

**Comment by bleeping-username** [comment]
Me too!

Mac OS 10.12.6
Photoshop CS6

Steps: Installed plugin to Photoshop plugins folder like normal. 
Started up Photoshop and open a .png file.
WebP is in the Save As pulldown options along with .psd, .tif, and all the rest.
When choosing webp, I get the dialog that it has to be saved as a copy. 
And it doesn't matter if I save as a copy or not, I get the same error.

I agree with others here. I refuse to upgrade from CS6. For one, I can't. CS6 works on OS 10.12. And I refuse to pay $600 a year to RENT something I already paid $600 to OWN (including the entire Adobe design family).

![Screen Shot 2020-11-02 at 6 02 40 AM](https://user-images.githubusercontent.com/73827365/97861011-1621f980-1cd1-11eb-86a0-be92eb77ccca.png)
![Screen Shot 2020-11-02 at 6 02 47 AM](https://user-images.githubusercontent.com/73827365/97861013-1621f980-1cd1-11eb-9caa-a20831e086ca.png)

![Screen Shot 2020-11-02 at 5 49 59 AM](https://user-images.githubusercontent.com/73827365/97860917-f094f000-1cd0-11eb-8c1e-094720f4fbf5.png)

**Comment by y-guyon** [comment]
> I agree with others here. I refuse to upgrade from CS6. For one, I can't. CS6 works on OS 10.12. And I refuse to pay $600 a year to RENT something I already paid $600 to OWN (including the entire Adobe design family).

These plugins may fit your needs:

- WebPFormat by Telegraphics: http://telegraphics.com.au/sw/product/WebPFormat
- AdobeWebM by fnordware: https://github.com/fnordware/AdobeWebM

**Comment by remcokalf** [comment]
Same here, Photoshop CS6. Cannot save 'because of a program error', with version 0.2.1 and "because the file could not be found" with later versions.

**Comment by rowancavanagh** [comment]
I've had this same issue today, on the latest Photoshop. Was there a resolution?

**Comment by bleeping-username** [comment]
I found this very useful. It's not a plugin but a separate little app.
https://www.xnview.com/en/xnconvert/
https://www.xnview.com/en/xnconvert/#downloads
I save the image as png from PS, then drag it to the window in XConvert. The settings are easy to figure out. I can batch process hundreds of files or just one. And best of all it's free, but certainly worth the donation of a cuppa.

**Comment by y-guyon** [comment]
> I've had this same issue today, on the latest Photoshop. Was there a resolution?

I just tried with WebPShop 0.4.3 and Photoshop 23.3.2. Reading and writing WebP files works for me. Could you share more about your setup (WebPShop, Photoshop and OS versions, provide source image and reproducing steps)?
