### ISSUE TITLE
Zero Length File

### ISSUE THREAD

**Issue by gimmees** [webmproject/WebPShop#8]
I installed the WebPShop_0_2_1_Win_x86 to Photoshop CS3, Version 10.0.  Everything appears to have installed correctly but when I save a file as .webp it save a zero length file (0 KB).  I've tried different file types and sizes and they all save the same.

**Comment by y-guyon** [comment]
Does the encoding parameters window appear when saving as a WebP file? Could you try with the latest version of Photoshop (20)?

**Comment by gimmees** [comment]
Yes, the dialog box appears and everything seems to work fine.  The file is saved with the .webp extension but it's zero length.  Unfortunately, I own the CS3 version and do not have access to 20.

**Comment by y-guyon** [comment]
Thank you for the report. Supporting the 2007 version is not the priority but if I get access to CS3 one day I might take a look.

**Comment by gimmees** [comment]
I understand.  It's a great product, I need to buck up and upgrade lol.
