### ISSUE TITLE
Cant get plug-in to work on Mac OS

### ISSUE THREAD

**Issue by fnavas00** [webmproject/WebPShop#9]
I keep getting error message:
<img width="425" alt="Screen Shot 2020-04-15 at 12 47 33 AM" src="https://user-images.githubusercontent.com/50570593/79302785-ec2ef400-7eb2-11ea-917c-d201f412d619.png">

**Comment by y-guyon** [comment]
Thank you for the report. This is the same issue as #3, could you try the workaround described there?

**Comment by fnavas00** [comment]
Thank you
